### ISSUE TITLE
[Tracking] Removal of GenServers

### ISSUE THREAD

**Issue by Arkenan** [lambdaclass/lambda_ethereum_consensus#1168]
This is a broad PR to track the removal of all GenServers before re-designing the architecture.

- [x] ForkChoice
- [x] Attestation
- [x] BeaconBlock
- [x] BlobSideCar
- [x] OperationsCollector
- [x] Metadata
- [x] Peerbook
- [x] BeaconChain: can be replaced by fork choice store db calls.
- [x] PendingBlocks. The more complex replacement is the periodic scheduled tasks and the fact that downloading awaits for an async process.
   - [x] #1122 
   - [x] #1121
- [x] IncomingRequestsReceiver: creates handler tasks. We need to remove the set_handler + the tasks should be started from libp2p port directly using a function in the handler module: #1192 
- [x] ExecutionChain: deposit tree is tricky. The rest is trivial. #1193 
- [x] Validator: maybe replaceable by modules that just react on slots. Calculating duties might be shared instead of repeated. Independent failure might be more complex if this is a needed feature. #1178 
- [x] ValidatorManager: Validators were removed naively touching the least amount of logic or state management. Removing the ValidatorManager may involve a bigger refactor. #1230

**Comment by rodrigo-o** [comment]
After removing the Validator GenServers, it was necessary to add one GenServer (instead of the previous N) for the ValidatorManager

**Comment by Arkenan** [comment]
Completed after #1244 🚀
