### ISSUE TITLE
[tracking] Fork choice spec tests

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#449]
These are all the test cases corresponding to the fork choice runner. **Please comment the one you are working on below so we avoid many people working on the same ones.**

**On Block Cases**
- [X] Basic
- [X] Incompatible justification update end of epoch
- [X] Incompatible justification update start of epoch
- [X] Justification update beginning of epoch
- [X] Justification update end of epoch
- [X] Justification withholding
- [X] Justification withholding reverse order
- [X] Justified update always if better
- [X] Justified update monotonic
- [X] Justified update not realized finality
- [X] New finalized slot is justified checkpoint ancestor
- [X] Not pull up current epoch block
- [X] On block bad parent root
- [X] On block before finalized
- [X] On block checkpoints
- [X] On block finalized skip slots
- [X] On block finalized skip slots not in skip chain
- [X] On block future block
- [X] Proposer boost
- [X] Proposer boost root same slot untimely block
- [X] Pull up on tick
- [X] Pull up past epoch block

**Ex Ante Cases**
- [X] Ex ante attestations is greater than proposer boost with boost
- [X] Ex ante sandwich with boost not sufficient
- [X] Ex ante sandwich with honest attestation
- [X] Ex ante sandwich without attestations
- [X] Ex ante vanilla

**Get Head Cases**
- [X] Chain no attestations
- [X] Discard equivocations on attester slashing
- [X] Discard equivocations slashed validator censoring
- [X] Filtered block tree
- [X] Genesis
- [X] Proposer boost correct head
- [X] Shorter chain but heavier weight
- [X] Split tie breaker no attestations
- [X] Voting source beyond two epoch
- [X] Voting source within two epoch

**Reorg Cases**
- [X] Delayed justification current epoch
- [X] Delayed justification previous epoch
- [X] Include votes another empty chain with enough ffg votes current epoch
- [X] Include votes another empty chain with enough ffg votes previous epoch
- [X] Include votes another empty chain without enough ffg votes current epoch
- [X] Simple attempted reorg delayed justification current epoch
- [X] Simple attempted reorg delayed justification previous epoch
- [X] Simple attempted reorg without enough ffg votes

**Disabled Cases**
- [X] Withholding attack
- [X] Withholding attack unviable honest chain
