### ISSUE TITLE
[tracking] Sanity blocks spec tests

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#450]
These are all the test cases corresponding to the sanity runner (for blocks). Please comment the one you are working on below so we avoid many people working on the same ones.

**Block Cases**
- [x] Activate and partial withdrawal max effective balance
- [x] Activate and partial withdrawal overdeposit
- [x] Attestation
- [x] Attester slashing
- [x] Balance driven status transitions
- [x] Bls change
- [x] Deposit and bls change
- [x] Deposit in block
- [x] Deposit top up
- [x] Duplicate attestation same block
- [x] Empty block transition
- [x] Empty block transition large validator set
- [x] Empty block transition no tx
- [x] Empty block transition randomized payload
- [x] Empty epoch transition
- [x] Empty epoch transition large validator set
- [x] Empty epoch transition not finalizing
- [x] Eth1 data votes consensus
- [x] Eth1 data votes no consensus
- [x] Exit and bls change
- [x] Full random operations 0
- [x] Full random operations 1
- [x] Full random operations 2
- [x] Full random operations 3
- [x] Full withdrawal in epoch transition
- [x] High proposer index
- [x] Historical batch
- [x] Inactivity scores full participation leaking
- [x] Inactivity scores leaking
- [x] Invalid all zeroed sig
- [x] Invalid duplicate attester slashing same block
- [x] Invalid duplicate bls changes same block
- [x] Invalid duplicate deposit same block
- [x] Invalid duplicate proposer slashings same block
- [x] Invalid duplicate validator exit same block
- [x] Invalid incorrect block sig
- [x] Invalid incorrect proposer index sig from expected proposer
- [x] Invalid incorrect proposer index sig from proposer index
- [x] Invalid incorrect state root
- [x] Invalid only increase deposit count
- [x] Invalid parent from same slot
- [x] Invalid prev slot block transition
- [x] Invalid same slot block transition
- [x] Invalid similar proposer slashings same block
- [x] Invalid two bls changes of different addresses same validator same block
- [x] Invalid withdrawal fail second block payload isnt compatible
- [x] Is execution enabled false
- [x] Many partial withdrawals in epoch transition
- [x] Multiple attester slashings no overlap
- [x] Multiple attester slashings partial overlap
- [x] Multiple different proposer slashings same block
- [x] Multiple different validator exits same block
- [x] Partial withdrawal in epoch transition
- [x] Proposer after inactive index
- [x] Proposer self slashing
- [x] Proposer slashing
- [x] Skipped slots
- [x] Slash and exit diff index
- [x] Slash and exit same index
- [x] Sync committee committee empty
- [x] Sync committee committee full
- [x] Sync committee committee half
- [x] Sync committee committee genesis empty
- [x] Sync committee committee genesis full
- [x] Sync committee committee genesis half
- [x] Top up and partial withdrawable validator
- [x] Top up to fully withdrawn validator
- [x] Voluntary exit
- [x] Withdrawal success two blocks

See: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/cf9cecff24ea177486fd9e08625a3edd4e4b671c/lib/spec/runners/sanity.ex

**Comment by MegaRedHand** [comment]
Done 🎉
